packages:
  - packages/*

catalog:
  react: ^19.0.0
  react-dom: ^19.0.0
  typescript: ^5.8.3
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  vite: ^7.0.0
  '@vitejs/plugin-react': ^4.6.0
  '@originjs/vite-plugin-federation': 1.4.1
