packages:
  - packages/*
  - libs/*

catalog:
  react: ^19.0.0
  react-dom: ^19.0.0
  typescript: ^5.8.3
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@originjs/vite-plugin-federation': 1.4.1
  '@rsbuild/core': ^1.4.2
  '@rsbuild/plugin-react': ^1.3.2
